# -*- coding: utf-8 -*-
"""Analyzing Financial Time Series: EDA and Hypothesis Testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kQdCTsdj9MzuyI84FumMoUWsDo0pJzOo
"""

#Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import io
from google.colab import files

# 1. UPLOAD EXCEL FILE
uploaded = files.upload()
filename = next(iter(uploaded))  # Automatically fetch the uploaded filename

# 2. LOAD AND CLEAN THE DATA
df = pd.read_excel(io.BytesIO(uploaded[filename]), parse_dates=['Date'])

# Remove unnamed columns (usually empty columns in Excel)
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

# Set 'Date' column as index and sort chronologically
df.set_index('Date', inplace=True)
df.sort_index(inplace=True)

# 3. EXPLORATORY DATA ANALYSIS (EDA)
print(" DATA INFO:")
print(df.info())

print(" MISSING VALUE CHECK:")
print(df.isnull().sum())

print("DESCRIPTIVE STATISTICS:")
print(df.describe())

# Correlation heatmap
plt.figure(figsize=(12, 6))
sns.heatmap(df.corr(), annot=False, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

# Time series plot for the first 3 assets
df.iloc[:, :3].plot(figsize=(12, 6))
plt.title("Time Series Plot of the First 3 Assets")
plt.xlabel("Date")
plt.ylabel("Value")
plt.grid(True)
plt.show()

# 4. HYPOTHESIS TEST: Is the mean daily return of the first asset different from zero?

# Calculate daily returns
returns = df.iloc[:, 0].pct_change().dropna()

# One-sample t-test
t_stat, p_val = stats.ttest_1samp(returns, 0)
print(f"\n HYPOTHESIS TEST RESULT for: {df.columns[0]}")
print(f"T-statistic: {t_stat:.4f}, P-value: {p_val:.4f}")

# Interpretation
if p_val < 0.05:
    print(" The mean daily return is statistically significantly different from zero (p < 0.05).")
else:
    print(" The mean daily return is NOT statistically significantly different from zero (p ≥ 0.05).")